[GOVALRT-5] Module rename.
salsadigitalauorg/govcms_alert pull request #1
Opened 2020-05-11 16:25 UTC by govindmaloo

https://salsadigital.atlassian.net/browse/GOVALRT-5

2020-05-12 04:12 UTC, govindmaloo commented
@sonnykt CI Tests are not configured properly, so failed. Let me know once fixed I will review them again.

2020-05-12 07:02 UTC, sonnykt requested changes

2020-05-12 07:02 UTC, sonnykt commented on js/alert_banner.js
> +  Drupal.behaviors.AlertsRestBlock = {
```suggestion
  Drupal.behaviors.AlertBannersRestBlock = {
```

2020-05-12 07:02 UTC, sonnykt commented on js/alert_banner.js
> +            Drupal.behaviors.AlertsRestBlock.attach(context, settings);
```suggestion
            Drupal.behaviors.AlertBannersRestBlock.attach(context, settings);
```

2020-05-12 07:02 UTC, sonnykt commented on js/alert_banner.js
> +      $('.alert-banners:not(.alerts-processed)', context).once('alerts_load').each(function (index, element) {
```suggestion
      $('.alert-banners:not(.alerts-processed)', context).once('alert_banners_load').each(function (index, element) {
```

2020-05-12 07:02 UTC, sonnykt commented on js/alert_banner.js
> +          endpoint = '/alerts?_format=json';
```suggestion
          endpoint = '/alert-banners?_format=json';
```

2020-05-12 07:02 UTC, sonnykt commented on alert_banner.module
> +  $endpoint = '/alerts?_format=json';
```suggestion
  $endpoint = '/alert-banners?_format=json';
```

2020-05-12 07:02 UTC, sonnykt commented on alert_banner.module
> +  // Retrieve the endpoint of GovCMS Alert Rest.
@govindmaloo No mention of GovCMS pls.

2020-05-12 07:02 UTC, sonnykt commented on alert_banner.routing.yml
> +    _title: 'Alert Settings'
```suggestion
    _title: 'Alert Banner Settings'
```

2020-05-12 07:02 UTC, sonnykt commented on README.md
>        * Alert date (newest first).
@govindmaloo Alert date no longer exists, and the `7 days` logic should also be removed from readme.

All references to the Date field must be removed.

2020-05-12 07:02 UTC, sonnykt commented on config/install/core.date_format.alert_date.yml
> +id: alert_date
```suggestion
id: alert_banner_date
```

All references of `govcms_alert` must be changed to `alert_banner`, not `alert`.

2020-05-12 07:02 UTC, sonnykt commented on config/install/core.entity_view_display.node.alert_banner.default.yml
> +      format_type: medium
```suggestion
      format_type: alert_banner_date
```
@govindmaloo the Alert Display Date must be displayed with the date format provided by the module, originally `govcms_alert_date`.

2020-05-12 07:02 UTC, sonnykt commented on config/install/field.field.node.alert_banner.field_alert_permanent.yml
>  description: 'Permanent alerts always display even if their alert date does not fall within 7 days. Alerts with future date will not show.'
```suggestion
description: 'Permanent alerts cannot be dismissed by visitors.'
```
@govindmaloo  please see the Solution Direction.

2020-05-12 07:02 UTC, sonnykt commented on config/install/views.view.alert_banners.yml
> +label: Alerts
```suggestion
label: Alert Banners
```

2020-05-12 07:02 UTC, sonnykt commented on config/install/views.view.alert_banners.yml
> +      path: alerts
```suggestion
      path: alert-banners
```

2020-05-12 07:02 UTC, sonnykt commented on config/install/views.view.alert_banners.yml
>        css_class: block-digitalwa-alerts
```suggestion
      css_class: block-alert-banners
```

2020-05-12 07:02 UTC, sonnykt commented on config/install/views.view.alert_banners.yml
> +            format_type: alert_date
```suggestion
            format_type: alert_banner_date
```

2020-05-12 07:02 UTC, sonnykt commented on css/alert_banner.css
> +.alert-banners article.node--type-alert {
@govindmaloo all references of `node--type-alert` need to be changed to `node--type-alert-banner`.

2020-05-12 07:02 UTC, sonnykt commented on css/alert_banner.css
> +.alert-banners article.node--type-alert .alert-message time {
```suggestion
.alert-banners article.node--type-alert-banner .alert-banner-message time {
```
@govindmaloo `govcms-alert` must be changed to `alert-banner`.

2020-05-12 07:02 UTC, sonnykt commented on js/alert_banner.js
> +      $('.alert-banners article.node--type-alert', context).each(function (index, element) {
```suggestion
      $('.alert-banners article.node--type-alert-banner', context).each(function (index, element) {
```

2020-05-12 07:02 UTC, sonnykt commented on js/alert_banner.js
> +      $('.alert-banners article.node--type-alert button.alert-close', context).click(function (event) {
```suggestion
      $('.alert-banners article.node--type-alert-banner button.alert-banner-close', context).click(function (event) {
```

2020-05-12 07:02 UTC, sonnykt commented on js/alert_banner.js
>          $('article.node--type-alert[data-alert-id="' + alert_id + '"]').remove();
```suggestion
        $('article.node--type-alert-banner[data-alert-id="' + alert_id + '"]').remove();
```

2020-05-12 07:02 UTC, sonnykt commented on js/alert_banner.js
> +              var $alert = $('<article role="article" data-alert-id="' + alert_item.alert_id + '" class="node node--type-alert"><div class="layout-container node__content"></div></article>');
```suggestion
              var $alert = $('<article role="article" data-alert-id="' + alert_item.alert_id + '" class="node node--type-alert-banner"><div class="layout-container node__content"></div></article>');
```

2020-05-12 07:02 UTC, sonnykt commented on js/alert_banner.js
> +                $('<div class="field clearfix alert-message">' + alert_message + '</div>')
```suggestion
                $('<div class="field clearfix alert-banner-message">' + alert_message + '</div>')
```

2020-05-12 07:02 UTC, sonnykt commented on js/alert_banner.js
> +                $('<div class="field clearfix alert-link">' + alert_item.link + '</div>')
```suggestion
                $('<div class="field clearfix alert-banner-link">' + alert_item.link + '</div>')
```

2020-05-12 07:02 UTC, sonnykt commented on js/alert_banner.js
> +                $alert.addClass('alert-link--none');
```suggestion
                $alert.addClass('alert-banner-link--none');
```

2020-05-12 07:02 UTC, sonnykt commented on js/alert_banner.js
> +                $('<button class="alert-close" data-alert-id="' + alert_item.alert_id + '" aria-label="' + label_dismiss + '"><span>' + label_dismiss + '</span></button>')
```suggestion
                $('<button class="alert-banner-close" data-alert-id="' + alert_item.alert_id + '" aria-label="' + label_dismiss + '"><span>' + label_dismiss + '</span></button>')
```

2020-05-14 14:20 UTC, govindmaloo commented
@sonnykt Updated js and css as per feedback.

Seven theme
<img width="1634" alt="Screenshot 2020-05-14 at 7 49 37 PM" src="https://user-images.githubusercontent.com/4437018/81945732-198ad100-961c-11ea-8624-e949f6c4b5a2.png">

Bartik theme
<img width="1392" alt="Screenshot 2020-05-14 at 7 49 46 PM" src="https://user-images.githubusercontent.com/4437018/81945742-1bed2b00-961c-11ea-968d-5d99e7b2e580.png">

2020-05-15 02:41 UTC, govindmaloo commented on js/alert_banner.js
> +  Drupal.behaviors.AlertsRestBlock = {
@sonnykt Updated

2020-05-15 02:41 UTC, govindmaloo commented on js/alert_banner.js
> +            Drupal.behaviors.AlertsRestBlock.attach(context, settings);
@sonnykt Updated

2020-05-15 02:41 UTC, govindmaloo commented on js/alert_banner.js
> +      $('.alert-banners:not(.alerts-processed)', context).once('alerts_load').each(function (index, element) {
@sonnykt Updated

2020-05-15 02:42 UTC, govindmaloo commented on js/alert_banner.js
> +          endpoint = '/alerts?_format=json';
@sonnykt Updated

2020-05-15 02:44 UTC, govindmaloo commented on js/alert_banner.js
> +              var $alert = $('<article role="article" data-alert-id="' + alert_item.alert_id + '" class="node node--type-alert"><div class="layout-container node__content"></div></article>');
@sonnykt Updated

2020-05-15 02:44 UTC, govindmaloo commented on js/alert_banner.js
> +                $('<div class="field clearfix alert-message">' + alert_message + '</div>')
@sonnykt Updated

2020-05-15 02:45 UTC, govindmaloo commented on js/alert_banner.js
> +                $('<div class="field clearfix alert-link">' + alert_item.link + '</div>')
@sonnykt updated

2020-05-15 02:45 UTC, govindmaloo commented on js/alert_banner.js
> +                $alert.addClass('alert-link--none');
@sonnykt Updated

2020-05-15 02:45 UTC, govindmaloo commented on js/alert_banner.js
> +                $('<button class="alert-close" data-alert-id="' + alert_item.alert_id + '" aria-label="' + label_dismiss + '"><span>' + label_dismiss + '</span></button>')
@sonnykt Updated

2020-05-15 02:46 UTC, govindmaloo commented on alert_banner.module
> +  $endpoint = '/alerts?_format=json';
@sonnykt Updated

2020-05-15 03:37 UTC, govindmaloo commented on alert_banner.module
> +  // Retrieve the endpoint of GovCMS Alert Rest.
@sonnykt Updated

2020-05-15 03:37 UTC, govindmaloo commented on alert_banner.routing.yml
> +    _title: 'Alert Settings'
@sonnykt Updated

2020-05-15 03:37 UTC, govindmaloo commented on README.md
>        * Alert date (newest first).
@sonnykt Updated

2020-05-15 03:38 UTC, govindmaloo commented on config/install/core.date_format.alert_date.yml
> +id: alert_date
@sonnykt Updated

2020-05-15 03:38 UTC, govindmaloo commented on config/install/core.entity_view_display.node.alert_banner.default.yml
> +      format_type: medium
@sonnykt Updated

2020-05-15 03:38 UTC, govindmaloo commented on config/install/field.field.node.alert_banner.field_alert_permanent.yml
>  description: 'Permanent alerts always display even if their alert date does not fall within 7 days. Alerts with future date will not show.'
@sonnykt Updated.

2020-05-15 03:40 UTC, govindmaloo commented on config/install/views.view.alert_banners.yml
> +label: Alerts
@sonnykt  Updated.

2020-05-15 03:40 UTC, govindmaloo commented on config/install/views.view.alert_banners.yml
>        css_class: block-digitalwa-alerts
@sonnykt Updated

2020-05-15 03:40 UTC, govindmaloo commented on config/install/views.view.alert_banners.yml
> +            format_type: alert_date
@sonnykt updated.

2020-05-15 03:41 UTC, govindmaloo commented on css/alert_banner.css
> +.alert-banners article.node--type-alert {
@sonnykt Updated all instance

2020-05-15 03:41 UTC, govindmaloo commented on css/alert_banner.css
> +.alert-banners article.node--type-alert .alert-message time {
@sonnykt Updated

2020-05-15 04:07 UTC, sonnykt approved these changes

2020-05-15 04:10 UTC, sonnykt requested changes

2020-05-15 04:10 UTC, sonnykt commented on alert_banner.install
> +use Drupal\user\Entity\Role;
@govindmaloo it's failing CI
```
FILE: ...leci/project/build/web/modules/alert_banner/alert_banner.install
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 9 | WARNING | [x] Unused use statement
   |         |     (Drupal.Classes.UnusedUseStatement.UnusedUse)
----------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
```

2020-05-15 04:30 UTC, govindmaloo commented on alert_banner.install
> +use Drupal\user\Entity\Role;
@sonnykt  fixed

2020-05-15 05:40 UTC, govindmaloo commented
@sonnykt All test pass.

2020-05-18 01:56 UTC, sonnykt approved these changes

2020-05-19 05:25 UTC, merged